spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory_svc_route
          predicates:
            - Path=/inventories/**
          uri: ${app.routes.inventory.uri}
        - id: order_svc_route
          predicates:
            - Path=/orders/**
          uri: ${app.routes.order.uri}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-svc
        url: /v3/api-docs
      - name: inventory-svc
        url: ${app.routes.inventory.api-docs}
      - name: order-svc
        url: ${app.routes.order.api-docs}

server:
  port: 8083
  forward-headers-strategy: framework

app:
  routes:
    inventory:
      uri: http://localhost:8082/inventories/
      api-docs: /inventories/v3/api-docs
    order:
      uri: http://localhost:8081/orders/
      api-docs: /orders/v3/api-docs
