apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-postgresql
  name: inventory-postgresql-service
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 25432
    protocol: TCP
    targetPort: 5432
  selector:
    service: inventory-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: inventory-postgresql-service
  template:
    metadata:
      labels:
        service: inventory-postgresql
        name: inventory-postgresql-service
    spec:
      containers:
      - image: 'postgres:12.22'
        name: inventories-db
        env:
          - name: POSTGRES_DB
            value: inventories
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: inventory-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inventory-secrets
                key: password