services:
  postgres:
    container_name: 'orders_db'
    image: 'postgres:12.22'
    environment:
      - 'POSTGRES_DB=orders'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '54321:5432'