services:
  postgres:
    container_name: 'inventories_db'
    image: 'postgres:12.22'
    environment:
      - 'POSTGRES_DB=inventories'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '25432:5432'